site_name: Clikt
repo_name: Clikt
repo_url: https://github.com/ajalt/clikt
site_description: "Clikt: Simple, powerful command line parser for Kotlin"
site_author: AJ Alt
remote_branch: gh-pages

copyright: 'Copyright &copy; 2020 AJ Alt'

theme:
  name: 'material'
  logo: img/wordmark_small.svg
  favicon: img/favicon.ico
  palette:
    primary: 'blue grey'
    accent: 'amber'

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Quickstart':
      - 'Basic Concepts': quickstart/
      - 'Printing to Stdout and Stderr': quickstart/#printing-to-stdout-and-stderr
      - 'Nesting Commands': quickstart/#nesting-commands
      - 'Adding Parameters': quickstart/#adding-parameters
      - 'Developing Command Line Applications With Gradle': quickstart/#developing-command-line-applications-with-gradle
  - 'Why Clikt?':
      - 'Why not a Kotlin library like kotlin-argparse or kotlinx.cli?': whyclikt/
      - 'Why not a Java library like JCommander?': whyclikt/#why-not-a-java-library-like-jcommander
  - 'Parameters':
      - 'Differences': parameters/
      - 'Parameter Names': parameters/#parameter-names
      - 'Parameter Types': parameters/#parameter-types
      - 'Built-In Types': parameters/#built-in-types
      - 'Custom Types': parameters/#custom-types
      - 'Parameter Validation': parameters/#parameter-validation
  - 'Options':
      - 'Basic Options': options/
      - 'Option Names': options/#option-names
      - 'Customizing Options': options/#customizing-options
      - 'Multi Value Options': options/#multi-value-options
      - 'Multiple Options': options/#multiple-options
      - 'Boolean Flag Options': options/#boolean-flag-options
      - 'Counted Flag Options': options/#counted-flag-options
      - 'Feature Switch Flags': options/#feature-switch-flags
      - 'Choice Options': options/#choice-options
      - 'Mutually Exclusive Option Groups': options/#mutually-exclusive-option-groups
      - 'Co-Occurring Option Groups': options/#co-occurring-option-groups
      - 'Choice and Switch Options With Groups': options/#choice-and-switch-options-with-groups
      - 'Prompting For Input': options/#prompting-for-input
      - 'Password Prompts': options/#password-prompts
      - 'Eager Options': options/#eager-options
      - 'Deprecating Options': options/#deprecating-options
      - 'Values From Environment Variables': options/#values-from-environment-variables
      - 'Values from Configuration Files': options/#values-from-configuration-files
      - 'Windows and Java-Style Option Prefixes': options/#windows-and-java-style-option-prefixes
      - 'Option Transformation Order': options/#option-transformation-order
  - 'Arguments':
      - 'Basic Arguments': arguments/
      - 'Variadic Arguments': arguments/#variadic-arguments
      - 'Option-Like Arguments ("--")': arguments/#option-like-arguments-using-
  - 'Commands':
      - 'Executing Nested Commands': commands/
      - 'Customizing Command Name': commands/#customizing-command-name
      - 'Passing Parameters': commands/#passing-parameters
      - 'Nested Handling And Contexts': commands/#nested-handling-and-contexts
      - 'Running Parent Command Without Children': commands/#running-parent-command-without-children
      - 'Customizing Contexts': commands/#customizing-contexts
      - 'Printing the Help Message When No Arguments Are Given': commands/#printing-the-help-message-when-no-arguments-are-given
      - 'Warnings and Other Messages': commands/#warnings-and-other-messages
      - 'Chaining and Repeating Subcommands': commands/#chaining-and-repeating-subcommands
  - 'Documenting Scripts':
      - 'Help Texts': documenting/
      - 'Preformatting Paragraphs': documenting/#preformatting-paragraphs
      - 'Subcommand Short Help': documenting/#subcommand-short-help
      - 'Help Option Customization': documenting/#help-option-customization
      - 'Default Values in Help': documenting/#default-values-in-help
      - 'Required Options in Help': documenting/#required-options-in-help
      - 'Grouping Options in Help': documenting/#grouping-options-in-help
  - 'Advanced Patterns':
      - 'Command Aliases': advanced/
      - 'Token Normalization': advanced/#token-normalization
      - 'Replacing stdin and stdout': advanced/#replacing-stdin-and-stdout
      - 'Argument Files ("@-files")': advanced/#command-line-argument-files-files
      - 'Testing your Clikt CLI': advanced/#testing-your-clikt-cli
  - 'Utilities':
      - 'Launching Editors': utilities/
      - 'Input Prompts': utilities/#input-prompts
      - 'Confirmation Prompts': utilities/#confirmation-prompts
  - 'Bash Autocomplete':
      - 'Supported Functionality': autocomplete/
      - 'Enabling Completion': autocomplete/#enabling-completion
      - 'Customizing Completions': autocomplete/#customizing-completions
      - 'Limitations': autocomplete/#limitations
  - 'Exception Handling':
      - 'Where are Exceptions Handled?': exceptions/
      - 'Handling Exceptions Manually': exceptions/#handling-exceptions-manually
      - 'Which Exceptions Exist?': exceptions/#which-exceptions-exist
  - 'API reference':
      - 'Commands and Exceptions': api/clikt/com.github.ajalt.clikt.core/
      - 'Options': api/clikt/com.github.ajalt.clikt.parameters.options/
      - 'Arguments': api/clikt/com.github.ajalt.clikt.parameters.arguments/
      - 'Parameter Type Conversions': api/clikt/com.github.ajalt.clikt.parameters.types/
      - 'Output Formatting': api/clikt/com.github.ajalt.clikt.output/
