#!/usr/bin/env bash
# Run one of the samples.
# The first argument must be the name of the sample task (e.g. echo).
# Any remaining arguments are forwarded to the sample's argv.
# Note that this does not support whitespace or nested quotes.

task=$1
shift 1
./gradlew :samples:${task}:run -PtaskArgs="$(printf '"%s" ' "$@"; echo "";)"
