enableFeaturePreview("GRADLE_METADATA")

include("clikt")
include("test")
include("samples:copy")
include("samples:repo")
include("samples:validation")
include("samples:aliases")
include("samples:helpformat")
include("samples:ansicolors")
include("samples:plugins")
include("samples:json")
