name: Publish

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  linux-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: check --stacktrace
  macos-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: macosX64Test --stacktrace
  windows-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: mingwX64Test --stacktrace

  deploy-mac-and-linux:
    needs: [ linux-tests, macos-tests, windows-tests ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch git tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Deploy to sonatype
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: :clikt:publish -PinferVersion=true
  deploy-windows:
    needs: [ linux-tests, macos-tests, windows-tests ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch git tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Deploy to sonatype
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: :clikt:publishMingwX64PublicationToMavenRepository -PinferVersion=true

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx5g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
